server:
  port : 7070

# spring:
#   security:
#     user:
#       name: admin
#       password: adminAb1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true